version: '3'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./autograder-server/media_root_dev:/protected

  django:
    restart: unless-stopped
    build:
      context: ./autograder-server
      dockerfile: Dockerfile-django-dev
    container_name: typescript-cli-django
    volumes:
      - ./autograder-server:/usr/src/app
    command: gunicorn --workers=1 autograder.wsgi:application --bind 0.0.0.0:8000 --error-logfile=- --access-logfile=-

    env_file:
      - ./autograder-server/_dev.env
    environment:
      # This gives us an extra way of verifying that we have X-Accel set up
      # correctly
      USE_NGINX_X_ACCEL: 'true'

      # Set to false to disable real authentication. Any other string value
      # will enable real authentication.
      # Then, using a browser plugin such as EditThisCookie, set the
      # cookie "username=<email>" to set which user you want to
      # authenticate as.
      USE_REAL_AUTH: 'false'

  postgres:
    restart: unless-stopped
    image: postgres:9.5
    container_name: typescript-cli-postgres
    expose:
      - "5432"
    command: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'

  redis:
    restart: unless-stopped
    image: redis:latest
    expose:
      - "6379"

  rabbitmq:
    image: 127.0.0.1:5000/rabbitmq
    restart: unless-stopped
    image: rabbitmq:latest
    hostname: rabbit
    expose:
      - "5672"
